### ISSUE TITLE
Define the Requirements

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/data-manager#1]
The BenchFlow data-manager handles the BenchFlow data.
It has to main responsibilities: 
1. Backup and Restore data to cheaper storages (e.g., Google Drive)
2. Perform versioned backups of the data
3. Access to data on demand (because it knows every data storage and the data state in the lifecycle)

@igormoreno reply to this issue with a comment (use markdown) where you elaborate on the requirement for point 1.

**Comment by igormoreno** [comment]
### Questions

What are the data sources?
Database, etc.

Versioning of large files?
Look into git-annex, git-lfs

Multiple data storage destinations?
How to interface with data storage? Authentication… SSH…

**Comment by igormoreno** [comment]
### Command line interface

```
software_name backup data_ID
software_name list backup [data_ID]
software_name restore [latest | timestamp] data_ID
```

**Comment by VincenzoFerme** [comment]
@igormoreno organise the note of our discussion and move it to a versioned file in the [documentation](https://github.com/benchflow/data-manager/tree/dev/documentation) folder

**Comment by VincenzoFerme** [comment]
This might help: 
![img_20160511_162137](https://cloud.githubusercontent.com/assets/7163641/15184305/f5cd8906-1794-11e6-85fe-2a4c133c3aa1.jpg)

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#84
