### ISSUE TITLE
Design of the Architecture of the Prototype Solution

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/data-manager#2]
Requirements defined in https://github.com/benchflow/data-manager/issues/1

@igormoreno use this issue to elaborate on the design of the architecture of the prototype solution for point 1 defined in https://github.com/benchflow/data-manager/issues/1

**Comment by igormoreno** [comment]
## Design

### Data sources

How to tell the data sources to not manipulate data that is being backed up?

Transfer of large files: synchronous or asynchronous?
How to download data from sources?
If asynchronous how to know that it is already completed? Use Filesystem watchdog?
If synchronous use multiple threads?
Use rsync?

How to add new data sources?
- Implement trait
    - Implementation has to be added to some list in the source code
    - Or use class loader to load new data source. To implement new data source implement interface and place 
      all implementations in a folder to be loaded by the software.
- Or just add new configuration file. That would be great but it's probably not feasible unless the data sources 
  can be classified in categories that operate uniformly

Interface for new data source:
- Operations:
  - mark as forbidden
  - mark as available
  - fetch data

### Backup storage

Where to store data in the file system?
`/Project_root_folder/data_ID/timestamp/data_source_name`

Timestamp may not be necessary if using versioning system (e.g. git-annex)

Metadata should be stored together with the data so the system is able to restore it.
What format should we use?
yml? Keyvalue pairs (bundle file format)?


### Main logic

#### Backup

- get data sources from data source provider

- for each data source
    mark data with given ID as forbidden

- for each data source
    fetch data and store in backup storage

- for each data source
    mark data with given ID as available

**Comment by VincenzoFerme** [comment]
@igormoreno organise the note of our discussion and move it to a versioned file in the [documentation](https://github.com/benchflow/data-manager/tree/dev/documentation) folder

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#85
