### ISSUE TITLE
Make Minio a data source

### ISSUE THREAD

**Issue by igormoreno** [benchflow/data-manager#24]

**Comment by igormoreno** [comment]
How is the test of components/services that interact with Minio handled?

**Comment by igormoreno** [comment]
How exactly are you managing buckets and object IDs?

**Comment by igormoreno** [comment]
When doing the backup of an experiment are all of the data sources queried? For example, when doing the backup of experiment ABC this system should: 
- retrieve rows in the tables in Cassandra related with that experiment
- retrieve (potentially many) objects in Minio related with that experiment
- retrieve data from other sources related with that experiment

right?

or different data sources are backed up separately?

**Comment by VincenzoFerme** [comment]
@igormoreno: right!

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#77
