### ISSUE TITLE
Backup manager

### ISSUE THREAD

**Issue by igormoreno** [benchflow/data-manager#32]
Extract most of the code in app/controllers/Application.scala
and move it to a backup manager making it easier to add new data sources.

It is important that the backup manager is well-documented so that it is clear what has to be updated/configured when someone needs to add new sources and destinations.

In the process create an abstraction to represent both
app/backuper/CassandraBackuper.scala
app/backuper/MinioBackuper.scala

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#98
